name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install
        run: yarn

      - name: Lint
        run: yarn lint
      
      - name: Jest (unit test)
        run: yarn jest

      - name: Cypress (integration test)
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start    

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.